In [84]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pickle
%matplotlib inline

In [2]:
df=pd.read_csv(r'C:\Users\91949\.ipynb_checkpoints\loanstat.csv')

In [3]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
for col in df.select_dtypes(exclude='object').columns:
    if df[col].isnull().any():
        df[col].fillna(df[col].median(),inplace=True)

In [5]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype == 'object':
            df[col].fillna(df[col].mode()[0],inplace=True)

In [6]:
df.columns.isnull().sum()

0

In [36]:
df.loc[df['Dependents']=='3+','Dependents']='3'

In [45]:
T=df.drop("Loan_ID",axis=1)

In [44]:
T.loc[T['Loan_Status']=='Y','Loan_Status']=1
T.loc[T['Loan_Status']=='N','Loan_Status']=0
T['Loan_Status']=T['Loan_Status'].astype(int)

In [54]:
T['Total']=T['ApplicantIncome']+T['CoapplicantIncome']
T['Debt/Income']=(T['LoanAmount']*1000)/T['Total']
T['EMI']=((T['LoanAmount']*(0.09)*((1.09)**T['Loan_Amount_Term']))/((1.09)**(T['Loan_Amount_Term']-1)))
T.drop(['LoanAmount','Loan_Amount_Term','ApplicantIncome','CoapplicantIncome'],axis=1,inplace=True)

KeyError: 'ApplicantIncome'

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\91949\\anaconda\\envs\\streamlit\\new1\\loanplus.csv'

In [55]:
T['Dependents']=T['Dependents'].astype(int)
T

,Gender,Married,Dependents,Education,Self_Employed,Credit_History,Property_Area,Loan_Status,Total,Debt/Income,EMI
0,Male,No,0,Graduate,No,1.0,Urban,Y,5850.0,21.880342,12.5568
1,Male,Yes,1,Graduate,No,1.0,Rural,N,6092.0,21.011162,12.5568
2,Male,Yes,0,Graduate,Yes,1.0,Urban,Y,3001.0,21.992669,6.4746
3,Male,Yes,0,Not Graduate,No,1.0,Urban,Y,4942.0,24.281667,11.7720
4,Male,No,0,Graduate,No,1.0,Urban,Y,6001.0,23.496084,13.8321
...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,1.0,Rural,Y,2901.0,24.474319,6.9651
610,Male,Yes,3,Graduate,No,1.0,Rural,Y,4107.0,9.739469,3.9240
611,Male,Yes,1,Graduate,No,1.0,Urban,Y,8313.0,30.434260,24.8193
612,Male,Yes,2,Graduate,No,1.0,Urban,Y,7584.0,24.657173,18.3447
613,Female,No,0,Graduate,Yes,0.0,Semiurban,N,4584.0,29.013962,13.0473

In [68]:
lis=[]
for col in T.columns:
    if T[col].dtype=='object':
        lis.append(col)
one= OneHotEncoder(handle_unknown='ignore',sparse=False)
K=pd.DataFrame(one.fit_transform(T[lis]))
K.index=T.index
L=T.drop(lis,axis=1)
M=pd.concat([K,L],axis=1)

In [69]:
Xt=M.drop(['Loan_Status'],axis=1)
yt=M['Loan_Status']
X_train,X_test,y_train,y_test=train_test_split(Xt,yt,train_size=0.7,test_size=0.3,random_state=1)
print(X_train.shape)
print(y_train.shape)

KeyError: "['Loan_Status'] not found in axis"

0.7837837837837838

FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

0.7837837837837838
{'max_depth': 3, 'min_samples_split': 3, 'n_estimators': 100}

In [78]:
X_train['Total_log']=np.log(X_train['Total'])
X_train.drop(['Total'],axis=1,inplace=True)
X_test['Total_log']=np.log(X_test['Total'])
X_test.drop(['Total'],axis=1,inplace=True)

<ipython-input-78-71e687c7a032>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Total_log']=np.log(X_test['Total'])
C:\Users\91949\anaconda\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [79]:
X_train
X_test

,0,1,2,3,4,5,6,7,8,9,10,Dependents,Credit_History,Debt/Income,EMI,Total_log
533,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1,1.0,17.422222,19.2276,9.328123
544,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0,1.0,27.717391,10.0062,8.210668
41,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0,1.0,15.599071,4.6107,8.010692
148,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0,1.0,19.286816,22.0725,9.364434
111,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0,1.0,26.415811,13.6359,8.568266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1,0.0,13.186813,17.6580,9.521495
491,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1,1.0,28.774752,18.2466,8.774004
42,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0,1.0,31.250000,7.3575,7.783224
530,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0,1.0,33.103448,21.1896,8.783396
457,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0,1.0,27.560937,16.9713,8.744647

In [82]:
parame={'penalty':('l1','l2',None), 'C':(0.001,0.01,0.1,1,10,100,1000)}
ld=LogisticRegression(max_iter=1000)
gd=GridSearchCV(ld,param_grid=parame,cv=5,n_jobs=3)
gd.fit(X_train,y_train)
gp=gd.best_estimator_
gpp=gp.predict(X_test)
print(accuracy_score(gpp,y_test))
print(gd.best_params_)

0.7891891891891892
{'C': 10, 'penalty': 'l2'}

In [91]:
param={'min_samples_split':np.arange(2,20), 'max_depth': np.arange(2,20),'n_estimators':np.arange(100,900,100)}
rd=RandomForestClassifier()
fd=GridSearchCV(rd,param_grid=param,cv=5,n_jobs=3)
fd.fit(X_train,y_train)
fp=fd.best_estimator_
fpp=fp.predict(X_test)
print(accuracy_score(fpp,y_test))
print(fd.best_params_)

0.7837837837837838
{'max_depth': 3, 'min_samples_split': 9, 'n_estimators': 200}

In [93]:
para={'min_samples_split':np.arange(2,26), 'max_depth': np.arange(2,30),'max_leaf_nodes':np.arange(2,50), 'criterion':['gini', 'entropy']}
cd=DecisionTreeClassifier()
md=GridSearchCV(cd,param_grid=para,cv=5,n_jobs=3)
md.fit(X_train,y_train)
pp=md.best_estimator_
ppp=pp.predict(X_test)
print(accuracy_score(ppp,y_test))
print(md.best_params_)

0.8054054054054054
{'criterion': 'gini', 'max_depth': 4, 'max_leaf_nodes': 8, 'min_samples_split': 6}